# Generated by Django 6.0.3 on 2026-03-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=200)),
                ('lote', models.CharField(max_length=100)),
                ('validade', models.DateField()),
                ('carencia_dias', models.IntegerField(blank=True, null=True)),
                ('quantidade', models.IntegerField()),
                ('dias_ate_vencimento', models.IntegerField(blank=True, null=True)),
                ('unidade_medida', models.CharField(max_length=50)),
            ],
        ),
    ]
